// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/mail.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmailEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	ConfirmedAt   int64                  `protobuf:"varint,3,opt,name=confirmed_at,json=confirmedAt,proto3" json:"confirmed_at,omitempty"`
	OptOut        bool                   `protobuf:"varint,4,opt,name=opt_out,json=optOut,proto3" json:"opt_out,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailEntry) Reset() {
	*x = EmailEntry{}
	mi := &file_proto_mail_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailEntry) ProtoMessage() {}

func (x *EmailEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mail_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailEntry.ProtoReflect.Descriptor instead.
func (*EmailEntry) Descriptor() ([]byte, []int) {
	return file_proto_mail_proto_rawDescGZIP(), []int{0}
}

func (x *EmailEntry) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EmailEntry) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *EmailEntry) GetConfirmedAt() int64 {
	if x != nil {
		return x.ConfirmedAt
	}
	return 0
}

func (x *EmailEntry) GetOptOut() bool {
	if x != nil {
		return x.OptOut
	}
	return false
}

type CreateEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmailAddr     string                 `protobuf:"bytes,1,opt,name=email_addr,json=emailAddr,proto3" json:"email_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEmailRequest) Reset() {
	*x = CreateEmailRequest{}
	mi := &file_proto_mail_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEmailRequest) ProtoMessage() {}

func (x *CreateEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mail_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEmailRequest.ProtoReflect.Descriptor instead.
func (*CreateEmailRequest) Descriptor() ([]byte, []int) {
	return file_proto_mail_proto_rawDescGZIP(), []int{1}
}

func (x *CreateEmailRequest) GetEmailAddr() string {
	if x != nil {
		return x.EmailAddr
	}
	return ""
}

type GetEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmailAddr     string                 `protobuf:"bytes,1,opt,name=email_addr,json=emailAddr,proto3" json:"email_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmailRequest) Reset() {
	*x = GetEmailRequest{}
	mi := &file_proto_mail_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmailRequest) ProtoMessage() {}

func (x *GetEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mail_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmailRequest.ProtoReflect.Descriptor instead.
func (*GetEmailRequest) Descriptor() ([]byte, []int) {
	return file_proto_mail_proto_rawDescGZIP(), []int{2}
}

func (x *GetEmailRequest) GetEmailAddr() string {
	if x != nil {
		return x.EmailAddr
	}
	return ""
}

type UpdateEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmailEntry    *EmailEntry            `protobuf:"bytes,1,opt,name=email_entry,json=emailEntry,proto3" json:"email_entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEmailRequest) Reset() {
	*x = UpdateEmailRequest{}
	mi := &file_proto_mail_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEmailRequest) ProtoMessage() {}

func (x *UpdateEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mail_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEmailRequest.ProtoReflect.Descriptor instead.
func (*UpdateEmailRequest) Descriptor() ([]byte, []int) {
	return file_proto_mail_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateEmailRequest) GetEmailEntry() *EmailEntry {
	if x != nil {
		return x.EmailEntry
	}
	return nil
}

type DeleteEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmailAddr     string                 `protobuf:"bytes,1,opt,name=email_addr,json=emailAddr,proto3" json:"email_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEmailRequest) Reset() {
	*x = DeleteEmailRequest{}
	mi := &file_proto_mail_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEmailRequest) ProtoMessage() {}

func (x *DeleteEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mail_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEmailRequest.ProtoReflect.Descriptor instead.
func (*DeleteEmailRequest) Descriptor() ([]byte, []int) {
	return file_proto_mail_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteEmailRequest) GetEmailAddr() string {
	if x != nil {
		return x.EmailAddr
	}
	return ""
}

type GetEmailBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmailBatchRequest) Reset() {
	*x = GetEmailBatchRequest{}
	mi := &file_proto_mail_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmailBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmailBatchRequest) ProtoMessage() {}

func (x *GetEmailBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mail_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmailBatchRequest.ProtoReflect.Descriptor instead.
func (*GetEmailBatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_mail_proto_rawDescGZIP(), []int{5}
}

func (x *GetEmailBatchRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetEmailBatchRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type EmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmailEntry    *EmailEntry            `protobuf:"bytes,1,opt,name=email_entry,json=emailEntry,proto3,oneof" json:"email_entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailResponse) Reset() {
	*x = EmailResponse{}
	mi := &file_proto_mail_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailResponse) ProtoMessage() {}

func (x *EmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mail_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailResponse.ProtoReflect.Descriptor instead.
func (*EmailResponse) Descriptor() ([]byte, []int) {
	return file_proto_mail_proto_rawDescGZIP(), []int{6}
}

func (x *EmailResponse) GetEmailEntry() *EmailEntry {
	if x != nil {
		return x.EmailEntry
	}
	return nil
}

type GetEmailBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmailEntries  []*EmailEntry          `protobuf:"bytes,1,rep,name=email_entries,json=emailEntries,proto3" json:"email_entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmailBatchResponse) Reset() {
	*x = GetEmailBatchResponse{}
	mi := &file_proto_mail_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmailBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmailBatchResponse) ProtoMessage() {}

func (x *GetEmailBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mail_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmailBatchResponse.ProtoReflect.Descriptor instead.
func (*GetEmailBatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_mail_proto_rawDescGZIP(), []int{7}
}

func (x *GetEmailBatchResponse) GetEmailEntries() []*EmailEntry {
	if x != nil {
		return x.EmailEntries
	}
	return nil
}

var File_proto_mail_proto protoreflect.FileDescriptor

const file_proto_mail_proto_rawDesc = "" +
	"\n" +
	"\x10proto/mail.proto\x12\x05proto\"n\n" +
	"\n" +
	"EmailEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12!\n" +
	"\fconfirmed_at\x18\x03 \x01(\x03R\vconfirmedAt\x12\x17\n" +
	"\aopt_out\x18\x04 \x01(\bR\x06optOut\"3\n" +
	"\x12CreateEmailRequest\x12\x1d\n" +
	"\n" +
	"email_addr\x18\x01 \x01(\tR\temailAddr\"0\n" +
	"\x0fGetEmailRequest\x12\x1d\n" +
	"\n" +
	"email_addr\x18\x01 \x01(\tR\temailAddr\"H\n" +
	"\x12UpdateEmailRequest\x122\n" +
	"\vemail_entry\x18\x01 \x01(\v2\x11.proto.EmailEntryR\n" +
	"emailEntry\"3\n" +
	"\x12DeleteEmailRequest\x12\x1d\n" +
	"\n" +
	"email_addr\x18\x01 \x01(\tR\temailAddr\"@\n" +
	"\x14GetEmailBatchRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"X\n" +
	"\rEmailResponse\x127\n" +
	"\vemail_entry\x18\x01 \x01(\v2\x11.proto.EmailEntryH\x00R\n" +
	"emailEntry\x88\x01\x01B\x0e\n" +
	"\f_email_entry\"O\n" +
	"\x15GetEmailBatchResponse\x126\n" +
	"\remail_entries\x18\x01 \x03(\v2\x11.proto.EmailEntryR\femailEntries2\xe3\x02\n" +
	"\x12MailingListService\x12@\n" +
	"\vCreateEmail\x12\x19.proto.CreateEmailRequest\x1a\x14.proto.EmailResponse\"\x00\x129\n" +
	"\aGetmail\x12\x16.proto.GetEmailRequest\x1a\x14.proto.EmailResponse\"\x00\x12@\n" +
	"\vUpdateEmail\x12\x19.proto.UpdateEmailRequest\x1a\x14.proto.EmailResponse\"\x00\x12@\n" +
	"\vDeleteEmail\x12\x19.proto.DeleteEmailRequest\x1a\x14.proto.EmailResponse\"\x00\x12L\n" +
	"\rGetEmailBatch\x12\x1b.proto.GetEmailBatchRequest\x1a\x1c.proto.GetEmailBatchResponse\"\x00B\x13Z\x11mailinglist/protob\x06proto3"

var (
	file_proto_mail_proto_rawDescOnce sync.Once
	file_proto_mail_proto_rawDescData []byte
)

func file_proto_mail_proto_rawDescGZIP() []byte {
	file_proto_mail_proto_rawDescOnce.Do(func() {
		file_proto_mail_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mail_proto_rawDesc), len(file_proto_mail_proto_rawDesc)))
	})
	return file_proto_mail_proto_rawDescData
}

var file_proto_mail_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_mail_proto_goTypes = []any{
	(*EmailEntry)(nil),            // 0: proto.EmailEntry
	(*CreateEmailRequest)(nil),    // 1: proto.CreateEmailRequest
	(*GetEmailRequest)(nil),       // 2: proto.GetEmailRequest
	(*UpdateEmailRequest)(nil),    // 3: proto.UpdateEmailRequest
	(*DeleteEmailRequest)(nil),    // 4: proto.DeleteEmailRequest
	(*GetEmailBatchRequest)(nil),  // 5: proto.GetEmailBatchRequest
	(*EmailResponse)(nil),         // 6: proto.EmailResponse
	(*GetEmailBatchResponse)(nil), // 7: proto.GetEmailBatchResponse
}
var file_proto_mail_proto_depIdxs = []int32{
	0, // 0: proto.UpdateEmailRequest.email_entry:type_name -> proto.EmailEntry
	0, // 1: proto.EmailResponse.email_entry:type_name -> proto.EmailEntry
	0, // 2: proto.GetEmailBatchResponse.email_entries:type_name -> proto.EmailEntry
	1, // 3: proto.MailingListService.CreateEmail:input_type -> proto.CreateEmailRequest
	2, // 4: proto.MailingListService.Getmail:input_type -> proto.GetEmailRequest
	3, // 5: proto.MailingListService.UpdateEmail:input_type -> proto.UpdateEmailRequest
	4, // 6: proto.MailingListService.DeleteEmail:input_type -> proto.DeleteEmailRequest
	5, // 7: proto.MailingListService.GetEmailBatch:input_type -> proto.GetEmailBatchRequest
	6, // 8: proto.MailingListService.CreateEmail:output_type -> proto.EmailResponse
	6, // 9: proto.MailingListService.Getmail:output_type -> proto.EmailResponse
	6, // 10: proto.MailingListService.UpdateEmail:output_type -> proto.EmailResponse
	6, // 11: proto.MailingListService.DeleteEmail:output_type -> proto.EmailResponse
	7, // 12: proto.MailingListService.GetEmailBatch:output_type -> proto.GetEmailBatchResponse
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_mail_proto_init() }
func file_proto_mail_proto_init() {
	if File_proto_mail_proto != nil {
		return
	}
	file_proto_mail_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mail_proto_rawDesc), len(file_proto_mail_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_mail_proto_goTypes,
		DependencyIndexes: file_proto_mail_proto_depIdxs,
		MessageInfos:      file_proto_mail_proto_msgTypes,
	}.Build()
	File_proto_mail_proto = out.File
	file_proto_mail_proto_goTypes = nil
	file_proto_mail_proto_depIdxs = nil
}
